# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer1.fabric.com:
  peer0.po1.fabric.com:
  peer1.po1.fabric.com:

networks:
  default:
    external:
      name: fab-net

services:

  orderer1.fabric.com:
    extends:
      file:   ./base/docker-compose-base.yaml
      service: orderer1.fabric.com
    container_name: orderer1.fabric.com
    # networks:
      # - fab-net

  peer0.po1.fabric.com:
    container_name: peer0.po1.fabric.com
    extends:
      file:  ./base/docker-compose-base.yaml
      service: peer0.po1.fabric.com
    # networks:
      # - fab-net
      
  peer1.po1.fabric.com:
    container_name: peer1.po1.fabric.com
    extends:
      file:  ./base/docker-compose-base.yaml
      service: peer1.po1.fabric.com
    # networks:
      # - fab-net
     
     

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.po1.fabric.com:7051
      - CORE_PEER_LOCALMSPID=po1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/po1.fabric.com/peers/peer0.po1.fabric.com/tls/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/po1.fabric.com/peers/peer0.po1.fabric.com/tls/keystore/key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/po1.fabric.com/peers/peer0.po1.fabric.com/tls/tlscacerts/tls-0-0-0-0-7151.pem
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/po1.fabric.com/users/Admin@po1.fabric.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    # ---CHANGED--- command needs to be commented out as we will be issuing commands explicitly, not using by any script
    
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - /tmp/hyperledger/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer1.fabric.com
    # networks:
      # - fab-net
